print("Welcome to the band name generator.")
print("What's the name of the city you grew up in?")
city = input()
print("What's your pet's name?")
pet = input()
print("Your band name could be:", city, pet)
print("Thank you for using the band name generator!")   
